Avoiding to copy unpacked zip when running locally

diff --git a/Tests/EndToEndTests/Examples/Image/Miscellaneous/CIFAR-10/06_RegressionSimple/run-test b/Tests/EndToEndTests/Examples/Image/Miscellaneous/CIFAR-10/06_RegressionSimple/run-test
--- a/Tests/EndToEndTests/Examples/Image/Miscellaneous/CIFAR-10/06_RegressionSimple/run-test
+++ b/Tests/EndToEndTests/Examples/Image/Miscellaneous/CIFAR-10/06_RegressionSimple/run-test
@@ -6,6 +6,7 @@ ConfigDir=$TEST_DIR/../../../../../../../Examples/Image/Miscellaneous/CIFAR-10
 
 # This test uses a large dataset which is not part of the CNTK repository itself
 # We use the dataset from an external location specified using an environment variable
+echo Looking for data in: $TEST_DATA_DIR
 if [[ ! -d $TEST_DATA_DIR || ! -e $TEST_DATA_DIR/cifar-10-batches-py ]]; then
     # Cannot find test data locally.
     # Try external test data directory (not part of the CNTK repository) as an alternative.
@@ -21,9 +22,13 @@ if [[ ! -d $TEST_DATA_DIR || ! -e $TEST_DATA_DIR/cifar-10-batches-py ]]; then
 
         # Copy the test data to the test run directory
         echo 'Copying test data to local directory'
-        DataDir=$TEST_RUN_DIR/TestData
-        mkdir $DataDir
-        cp -R $DataSourceDir/cifar-10-batches-py $DataDir || exit $?
+        CopyDir=$TEST_RUN_DIR/cifar-10-batches-py
+        mkdir $CopyDir
+		# copying recursively also copies the unpacked zip
+		# copying * results in exit code 0 due to omitting the directory
+        cp $DataSourceDir/cifar-10-batches-py/*.xml $CopyDir || exit $?
+        cp $DataSourceDir/cifar-10-batches-py/*.zip $CopyDir || exit $?
+        cp $DataSourceDir/cifar-10-batches-py/*.txt $CopyDir || exit $?
         Copied=1
         echo 'Done copying data'
     else
@@ -33,11 +38,13 @@ if [[ ! -d $TEST_DATA_DIR || ! -e $TEST_DATA_DIR/cifar-10-batches-py ]]; then
 fi
 
 # cntkrun <CNTK config file name> <additional CNTK args>
+# setting thye DataDir to the run dir, since the cntk config expects data and ampping files in '$dataDir$/cifar-10-batches-py/'
+DataDir=$TEST_RUN_DIR
 echo 'Starting cntk run'
 cntkrun 06_RegressionSimple.cntk "[command=TrainConvNet:Test] stderr=-"
 ExitCode=$?
 
 # Delete the test data if copied
-[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"
+#[[ "$Copied" -eq "1" ]] && rm -rf "$CopyDir"
 
 exit $ExitCode
